name: WorkshopManager

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [7.2, 7.3, 7.4, 8.0, 8.1]

    name: PHP ${{ matrix.php }}

    env:
      PHP_INI_VALUES: phar.readonly=0

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer:v2
          ini-values: ${{ env.PHP_INI_VALUES }}

      - name: Install Dependencies
        run: composer update

      - name: Run phpunit tests
        run: |
          mkdir -p build/logs
          export COLUMNS=200
          vendor/bin/phpunit --coverage-clover ./build/logs/clover.xml

      - name: Run phpcs
        run: composer cs

      - name: Run phpstan
        run: composer static

      - name: Coverage upload
        uses: codecov/codecov-action@v3
        if: matrix.php == '7.4'
        with:
          files: ./build/logs/clover.xml
          fail_ci_if_error: true

      - name: Build phar
        if: matrix.php == '7.2' && github.ref == 'refs/heads/master'
        run: |
          echo "Building phar"
          ./bin/deploy.sh



